[package]
name = "voj_backend"
version = "0.1.2"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web="^3"
serde="^1.0"
serde_json="^1.0"
serde_derive="^1.0"
anyhow="^1.0"
chrono="^0.4.15"
dotenv="^0.15"
env_logger=""
log=""
r2d2_postgres=""
r2d2=""
jsonwebtoken = "7.2.0"
futures=""
futures-util=""
